name: GraphQL-API
region: eu-west-3
cloud: aws
# watcher: true

stages:
    - dev
    - prod

functions:
    graphql:
        name: GraphQL-Provider
        description: Provide a serverless GraphQL API
        handler: src.handler
        runtime: nodejs12.x
        environ:
            EMAIL: !env EMAIL
            PASS: !env PASS
        memory: 1024
        timeout: 25

    image_processing:
        name: Image-Processing
        description: Provide a serverless image processing system
        handler: src.handler
        runtime: python3.7
        layers:
            - $layer1
        memory: 1024
        timeout: 25

layers:
    layer1:
        name: PythonDeps
        description: Contains all needed python dependencies
        runtimes:
            - python3.8
            - python3.7
            - python3.6
        before-script: >
            pip install -r requirements.txt --target ./dependencies;
        source: ./src

# apis:
#     PeachAPI:
#         name: PeachAPI
#         description: Serverless Peach API
#         type: REGIONAL
#         stages:
#             - dev
#             - prod
#         routes:
#             /graphql:
#                 method: ANY
#                 attach: GraphQL-Provider
#             /todo:
#                 method: GET
#                 childs:
#                     /create:
#                         method: PUT
#                     /delete:
#                         method: DELETE
#             /get:
#                 childs:
#                     /{id}:
#                         method: GET
